### ISSUE TITLE
Add correct subdomain prefix for etherescan links

### ISSUE THREAD

**Issue by jopasserat** [ensdomains/ens-app#108]
Just a minor UX tweak: when browsing the records for a given name (ex: https://manager.ens.domains/name/michalzalecki.test), it would be nice to have the links pointing to the right Etherscan subdomain according to the current account in the injected web3.

For instance, when browsing [this name](https://manager.ens.domains/name/michalzalecki.test), registered in rinkeby, the owner, resolver and address links all point to the mainnet's version of Etherscan.

[Main net Owner => "no matching entries"](http://etherscan.io/address/0x7D20cb28C496A76173eE828ecacfB08dEB379E8d)
[Rinkeby Owner => success](http://rinkeby.etherscan.io/address/0x7D20cb28C496A76173eE828ecacfB08dEB379E8d)

Related to #25

**Comment by djuanit0x** [comment]
Hi, I am quite interested in this issue. Should I update the EtherScanLink component to use the getEtherScanAddr function in the util.js? However, the issue is EtherScanLink is not an async function, and change it to an async function will result for the EtherScanLink to be wrapped by a promise. Do you have any advice and other suggestion related to this issue?

**Comment by jefflau** [comment]
@djuanit0x Sorry I did not see this. You can change `EtherScanLink` to call `getEtherScanAddr` inside a `useEffect` and then update the etherscan address when it's loaded and not show a link (or just show text) until it's loaded

**Comment by makoto** [comment]
It now points to test net etherscan
