### ISSUE TITLE
Name search breaks when search query contains . characters

### ISSUE THREAD

**Issue by ClosedGL2** [ensdomains/ens-app#1099]
When I search for a domain name with one period character (eg. hello.world), it doesn't search and the following text shows up:
```
{"graphQLErrors":[],"networkError":{},"message":"Network error: k is undefined"}
```
When I search for a domain name with two or more period characters (eg. one.two.three), the page becomes blank.

1. Go to app.ens.domains
2. Type a domain name with one "." character to get no results and the "k is undefined" error.
3. Type a domain name with two or more "." characters to get a blank page.

When I type "hello.world" or "one.two.three", I would have expected to get a result for "hello.world.eth" or "one.two.three.eth".

**Comment by makoto** [comment]
Hi, I fixed the error so it shouldn't show graphQLErrors.

In terms of your expected behavior, if you type `hello.world` it just gets redirected to https://app.ens.domains/name/hello.world . It will only append `.eth` if you don't have any `.` . This is because we are soon integrating with any DNS names (eg. .com, .io, .org) just like .xyz (eg: https://app.ens.domains/name/argent.xyz) so `hello.world` can be a valid name if tld exists (we don't check if each tld actually exists so it will just show `no owner` unless owned by someone.
