### ISSUE TITLE
About the content hash of Swarm

### ISSUE THREAD

**Issue by hibbb** [ensdomains/ens-app#1114]
**Describe the bug**
The swarm content hash on the name page (such as https://app.ens.domains/name/liubenben.eth) is using an outdated gateway: swarm-gateways.net, and the link of the swarm content can't bring user to the correct page. 

Maybe you should use the new official gateway: gateway.ethswarm.org.

Another problem is that the eth.link service haven't provide the swarm content support.

**To Reproduce**

1. Go to https://app.ens.domains/name/liubenben.eth
2. Click on 'bzz://e0e170...' behind the tag named "content"
3. See error: 404 Not Found

![image](https://user-images.githubusercontent.com/233410/114111428-94339d80-990c-11eb-993d-0197b447e967.png)

**Expected behavior**
It should be shown with a right page user set in the resolver. 
https://gateway.ethswarm.org/bzz/e0e170cab59f05e45804ad8382fe31115478231acc478a2d40402c35a68f5c32/

![image](https://user-images.githubusercontent.com/233410/114111441-9b5aab80-990c-11eb-81f9-cde03f2ae5cd.png)

**Comment by chaserene** [comment]
hey, this is because the ENS manager app uses an old Swarm gateway that's been deprecated (https://swarm-gateways.net/).

a new and currently functional gateway, running on the current Goerli testnet deployment, can be found here: https://gateway.ethswarm.org/

@makoto could you update the manager interface to use this? the URL structure is this: 
`https://gateway.ethswarm.org/files/<swarmContentHash>`

**Comment by makoto** [comment]
@chaserene is the `files` part of https://gateway.ethswarm.org/files/ always `bzz` or do we have anything else?

**Comment by chaserene** [comment]
@makoto I'm not fully qualified to say, but I think for requesting content it's always ʻbzzʻ. their other protocol I know of is ʻpssʻ but that's for messaging.
