### ISSUE TITLE
Some emoji is treated as malmormed

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#1167]
eg:🦚

https://app.ens.domains/search/%F0%9F%A6%9A

<img width="1039" alt="Screenshot 2021-06-07 at 14 25 01" src="https://user-images.githubusercontent.com/2630/121024498-2dabee00-c79c-11eb-8e33-67c9ef8dbb7d.png">

**Comment by mdtanrikulu** [comment]
Seems like the issue is caused by the sub-dependency of the `@ensdomains/ui`. 
It uses [eth-ens-namehash](https://github.com/danfinlay/eth-ens-namehash)@^2.0.8, which uses [idna-uts46-hx](https://github.com/hexonet/idna-uts46)@^2.3.1. 

Updating `idna-uts46` to latest version solves the issue. Maybe we can create a ticket for the `eth-ens-namehash` repo.

**Comment by the-emerald** [comment]
Unfortunately it looks like [danfinlay/eth-ens-namehash#25](https://github.com/danfinlay/eth-ens-namehash/issues/25) is unmaintained? It has not been touched since 2018. A workaround would be nice - mostly because I have an emoji ENS name I want that this issue is blocking me from registering.
