### ISSUE TITLE
Primary name cannot be set through ens-app for a sub-domain with custom resolver

### ISSUE THREAD

**Issue by hodlthedoor** [ensdomains/ens-app#1529]
**Description**
No .pcc.eth sub-domains that have a custom resolver are able to be set as primary name through the ens-app. 

**To Reproduce**

1. Register ENS sub-domain with a custom resolver. hodl.pcc.eth is an example
2. Navigate to the account management page and the sub-domain does not show in the drop-down for setting primary address

**Expected behavior**
Expect hodl.pcc.eth to show in the drop-down with other ENS that resolve to that address

**Additional context**
I mentioned this problem to coltron.eth he asked me to raise this as an issue here. The sub-domain can still be set directly to the reverse registar contract using the setName function.

**Comment by makoto** [comment]
Hi, `hodl.pcc.eth` doesn't seem to be created. Do you have an example subdomain which has ETH record set (for example `zeus.pcc.eth` does not have ETH record set  It also helps me if you can point me to the transaction id when you did create subdomain and set resolver.

**Comment by hodlthedoor** [comment]
Hi

Yes, hodl.pcc.eth resolves to my wallet.

https://etherscan.io/enslookup-search?search=hodl.pcc.eth



Sent from Mail for Windows

**Comment by makoto** [comment]
Can you also set ETH address into hodl.pcc.eth ? Currently it's empty and the primary name checks if the name points to the address you are trying to set primary name for.

<img width="780" alt="Screenshot 2022-06-17 at 11 38 25" src="https://user-images.githubusercontent.com/2630/174282551-54855766-ed94-41b3-8688-27ff2c94f7ba.png">

**Comment by hodlthedoor** [comment]
The ETH address is set. Is the issue that the event is not emitted? So ENS-app is not picking it up.

If you check using Metamask then you can see that hodl.pcc.eth correctly resolves.




Sent from Mail for Windows

**Comment by makoto** [comment]
oh I see. so this is the custom resolver you made by yourself. I can see text record because your resolver contract has `setText` that emits `emit TextChanged(node, key, key);`. Do you have `setAddr` equivalent that emit `AddrChanged` ?

The address page is fetching the list of available domain to set primary name from this subgraph query https://github.com/ensdomains/ens-app/blob/dev/src/graphql/queries.js#L152  and  `resolvedAddress` is [updated at](https://github.com/ensdomains/ens-subgraph/search?q=resolvedAddress) `registry. NewResolverEvent` and `resolver.AddrChangedEvent ` so your custom resolver has  emit these event accordingly for the graph indexer to pick up

**Comment by hodlthedoor** [comment]
No, I was unable to add the address changed event, because this can be triggered from the NFT contract that the resolver links to and the NFT contract was written many months before.

I understand what the issue is now though so you can close this if you like. We have a workaround for setting the primary address.

Regards,


Sent from Mail for Windows
