### ISSUE TITLE
Update "Resolver" flow for Newly Registered Name

### ISSUE THREAD

**Issue by chris-remus** [ensdomains/ens-app#216]
Change from this - 

<img width="1458" alt="Screen Shot 2019-04-29 at 3 52 44 PM" src="https://user-images.githubusercontent.com/6430200/56922714-e28c6080-6a96-11e9-8ba8-0f4f60d410d6.png">

To this - 

<img width="853" alt="Screen Shot 2019-04-29 at 3 53 29 PM" src="https://user-images.githubusercontent.com/6430200/56922759-f9cb4e00-6a96-11e9-8e86-5134aa5ebb43.png">

See discussion [here](https://discuss.ens.domains/t/permanent-registrar-ux-ui-design-feedback/824/29).

**Comment by makoto** [comment]
This has been the known UI issues for ages. Is this mandatory to be added before the permanent registrar migration? If we do this, we should also add default address set to the same one as the one of registrant or controller but these tiny tweaks may bring in unknown bugs. I would suggest we limit last minute changes to bug fixes rather than small enhancements.

**Comment by jefflau** [comment]
I agree. I don't think this is necessary for the permanent registrar release and it should be discussed and designed specifically if we are going to make the change. I'm removing the permanent registrar tag from this as I don't think it has been agreed upon to do this for the weekend release and being a less than a week before release I strongly recommend against any UI changes.

**Comment by jefflau** [comment]
I've removed permanent registrar label for now

**Comment by chris-remus** [comment]
@jefflau & @makoto Fair enough. I've created and assigned a "next" label to it. My sense is we should do this shortly after launch, as this could favorably impact adoption quite a bit.

**Comment by Magicking** [comment]
The new flow seemed to have been implemented, as a first-time user the "Use public resolver" label alongside the **Save** button didn't blocked me too much, I would have loved a tiny **?** next to the label to knew what it implied beforehand.

Also, there seemed to be a but because it was not showing "TX Pending" and I ended up setting 2 times the Registrar instead of waiting for the transaction to be included in a block.
