### ISSUE TITLE
supporting Multisigs, hardware wallets and other signing providers

### ISSUE THREAD

**Issue by lyricalpolymath** [ensdomains/ens-app#334]
right now ENS supports only MM
but there are concrete needs for other signing providers
an example from a user in Gitter that needs to manage a domain from a Multisig.
we should provide a UI for simplifying this

![Screenshot 2019-05-23 at 18 39 23](https://user-images.githubusercontent.com/516744/58271248-ece70500-7d8b-11e9-8f62-ccda63757f89.jpg)

for **hardware wallets**
supporting Frame seems like a simple solution
https://frame.sh/

for mobile wallets (where the user doesn't surf the manage directly from mobile)
walletconnect seems robust right now
https://walletconnect.org/

**Comment by makoto** [comment]
Walletconnect requires to host [a bridge server](https://docs.walletconnect.org/tech-spec) which I prefer to wait until we can just use public bridge server rather than hosting our own (unless we decide to have our backend). 

With regards to Frame, what do we have to do? By watching [their video](https://youtu.be/wlZWLiy2GD0?t=566) , it has its own chrome extension which injects a provider just like metamask or any other mobile wallet (Opera, Status.im). If that's the case, we don't need anything to support Frame.

Allowing user to  manage manager from multisig account is interesting (and transferring registrant ownership to multisig is probably a good security practice to manage ENS names) but not sure if it's managed at Dapp level, or should be provided by the multisig provider (eg: Gnosis safe). Are there any existing Dapp which provides the UI?

**Comment by lyricalpolymath** [comment]
that's a good question.. will search if there are other multisig enabled dapps out there... possibly maker and other financial dapps?

for the multisig, 
maybe we can `provide the ens updating call as raw data to use in the multisig payload`
like homotopycolimit said.
this might imply just a checkbox `is this TX for a multisig?` that if checked reveals the raw TX information to the user for easy copy and paste

maybe there is need for a custom UI if we can detect if an "owner" or "controller" is actually a multisig.

I have a multisig on ropsten..will test how the process works and see how we could improve the flow
if you want to maybe label this #ux and #research or something else

**Comment by sche** [comment]
Are there any updates on this issue?

**Comment by makoto** [comment]
Multisig is now supported by Gnosis safe and other hardware should work through Metemask
