### ISSUE TITLE
Manager shows incorrect registration date for names expiring before May 4 2020

### ISSUE THREAD

**Issue by Arachnid** [ensdomains/ens-app#363]
For example, https://manager.ens.domains/name/omnivorous.eth expired on June 4, but the manager says it doesn't expire until May 4 2020.

**Comment by jefflau** [comment]
Can you look into this @makoto?

**Comment by makoto** [comment]
@arachnid the problem looks to me more of the fact that `.available(id)` returns `false` despite the fact that it already expired (you can check at https://etherscan.io/address/0xFaC7BEA255a6990f749363002136aF6556b31e04#readContract by passing labelhash of 0xbdd753d3174c6057d4300908f42291e9a9b74047fe6074903970054908887b68). If it returns `true`, then the page will render registration page. What is the condition of this happening? Looks like an invariant is violated.

<img width="1475" alt="Screenshot 2019-07-09 at 11 10 59" src="https://user-images.githubusercontent.com/2630/60879980-a0239480-a23a-11e9-8aa9-73817059bb23.png">

**Comment by makoto** [comment]
Also checked the availability from controller and it is not available.

https://etherscan.io/address/0xF0AD5cAd05e10572EfcEB849f6Ff0c68f9700455#readContract

<img width="473" alt="Screenshot 2019-07-09 at 11 31 56" src="https://user-images.githubusercontent.com/2630/60881562-df9fb000-a23d-11e9-8ecc-20ed616f9606.png">

**Comment by makoto** [comment]
Ok, with further investigation, realised that the name is in the grace period.
I can fix showing correct expiration period and it looks like this.

<img width="761" alt="Screenshot 2019-07-09 at 12 43 47" src="https://user-images.githubusercontent.com/2630/60885374-6016de80-a247-11e9-959d-2642dfef0f28.png">

The app is not showing registrant information nor renewal button because it depends on `ownerOf` function which does not take grace period into consideration.

```
    function ownerOf(uint256 tokenId) public view returns (address) {
        require(expiries[tokenId] > now);
        return super.ownerOf(tokenId);
    }
```

First of all, is the above logic of `ownerOf` correct?

If yes, what is the condition to allow user to renew? If I rely on `available:false` that allows legacy registrar to renew as well I think (unless I specifically check if we are currently in the grace period).

**Comment by Arachnid** [comment]
@makoto The logic for `ownerOf` is correct - technically it has no owner during the grace period. You're right that this leaves us with a bit of a problem identifying what names can be renewed. Can you simply call `estimateGas` on the `renew` function, and show the UI if it doesn't throw an exception?

**Comment by makoto** [comment]
Fixed at https://github.com/ensdomains/ens-app/pull/382
