### ISSUE TITLE
Search results not displaying on Firefox

### ISSUE THREAD

**Issue by chris-remus** [ensdomains/ens-app#365]
Firefox Quantum Version 67.0.4

Search results not displaying. The wheel just keeps spinning.

<img width="1274" alt="Screen Shot 2019-07-01 at 2 09 25 PM" src="https://user-images.githubusercontent.com/6430200/60457498-2d973100-9c0a-11e9-8e0a-ad2d88aee368.png">

It works OK on Brave Version 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit).

**Comment by chrisschaub** [comment]
Not just firefox, but Chrome Ubuntu 18.04 as well. I think this commit 

https://github.com/ensdomains/ens-app/commit/0895cfa018c2f9de851e919315523e347ebdd39a

removed importing web3, maybe. It was working great a week ago when I last used it. I've removed metamask, re-installed, shut off all plugins, still no luck. The blank screen is because there are "No Acconts" present. If you go to the main screen, you will see "No Accounts". On the screen referenced above, this condition causes the code that bootstraps the permanent registrar to fail with "Error getting permanent registrar entry TypeError: Cannot read property 'permanentRegistrar' of undefined" ... so the blank screen is due to this JS error being thrown.

**Comment by jefflau** [comment]
@chrisschaub Thanks, it's some regression bugs from moving away from web3 and using ethersjs. I'm looking through it today. I think it's something to do with when metamask is not logged in (waiting for password) or if metamask crashes.

**Comment by jefflau** [comment]
@chrisschaub I'm not sure if this is related to the Firefox bug - but can you check if you still get that error?

**Comment by chris-remus** [comment]
Looking good on Firefox and Brave now 👍
