### ISSUE TITLE
Shows blank page on subdomain with Chinese character

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens-app#378]
> Page is blank when there is a non-english utf8 chinese character present in the subdomain page .
> Example URL : https://manager.ens.domains/name/example.eth/subdomains
> 
> However, I can still successfully set resolver in URL like https://manager.ens.domains/name/中文.example.eth .. So it's only a UI problem..

Originally opened by @afool41 on the UI library repo

**Comment by jefflau** [comment]
>I don't know if example.eth has a utf8 chinese character subdomain, I was referring to example.eth as >an example only..
>The specific domain I know has utf8-chinese subdomains is cryptogr.eth - >https://manager.ens.domains/name/cryptogr.eth/subdomains

**Comment by makoto** [comment]
I don't think this is an issue any more since migrated into thegraph version. Because none of non english characters are in the image, it just gets shown as labelhash.

<img width="1346" alt="Screenshot 2019-09-03 at 11 50 34" src="https://user-images.githubusercontent.com/2630/64167384-127eb280-ce41-11e9-82f1-75ae692d8f2b.png">
