### ISSUE TITLE
Doesn't allow you to transfer Registrant to 0x000...

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#477]
MetaMask doesn't even pop up when you attempt to do this.

**Comment by makoto** [comment]
It turned out hat it is a feature than a bug.
It used to be able to do it but when we migrated to the permanent registrar we changed to use ERC721 and ERC721 apparently prohibits sending owner to 0x https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L304

And it is defined in the EIP 721 itself https://github.com/ethereum/EIPs/blame/master/EIPS/eip-721.md#L83

Unless we abandon ENS name to be ERC721 compliant, I don't think there is anything you can do.
