### ISSUE TITLE
Add redirect banner for 3-6 character names

### ISSUE THREAD

**Issue by chris-remus** [ensdomains/ens-app#478]
Please add a banner to search result/name detail pages that indicate 3-6 character name auctions are currently underway at [OpenSea](https://opensea.io/ens)?

<img width="1656" alt="Screen Shot 2019-09-11 at 4 10 04 PM" src="https://user-images.githubusercontent.com/6430200/64874823-d229ec00-d619-11e9-8598-00d5d5f82682.png">

**Comment by jefflau** [comment]
I have sent Becca a message for a design for this @rliebert90

**Comment by rliebert90** [comment]
@chris-remus @jefflau I designed something super basic for this a while back. If you type in jsl.eth you see it. Looks like this: 

<img width="1248" alt="Screen Shot 2019-09-16 at 3 28 39 PM" src="https://user-images.githubusercontent.com/45074845/64987235-c9921980-d896-11e9-87a9-70be168e6f40.png">

@jefflau is there a way to jump directly into the name detail instead of seeing the search results? If you can't get around this (without the user adding .eth to the name when searching), the hover state of the search result could say 'in auction' and instead of a grey bar, we could use another color to make it obvious that it's not just another unavailable name. 

Maybe orange, with 'in auction'. If they want to get to open sea's, they can by clicking into the name and getting the detail view. Would look like this: 

<img width="926" alt="Screen Shot 2019-09-16 at 3 35 22 PM" src="https://user-images.githubusercontent.com/45074845/64987690-bf244f80-d897-11e9-976d-7e2e3f5ff73e.png">

**Comment by jefflau** [comment]
I've added the little banner 'in auction' as Becca has suggested
