### ISSUE TITLE
Mobile version needs tweaking, fields aren't big enough, can't read what's in them etc

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#506]
While the Manager is mobile friendly, the font in the drop down menus need to be smaller so they don't get cut off, et al. Right now it's very hard to use on mobile, and many wallets are mobile and will be directing their users there.

**Comment by makoto** [comment]
Do you mean drop down on text/other addresses ? 

![Screenshot_20191030-111144](https://user-images.githubusercontent.com/2630/67853499-946c1e80-fb06-11e9-9414-cbfbc88eae70.jpg)

Rather than making font smaller, I think it's better to have each dropdown menu and value field full width. Any thoughts? @jefflau and Becca?

**Comment by makoto** [comment]
`Public Resolver remains very confusing.` that's a whole different topic. please raise it to @Arachnid rather than discussing in this issue.
