### ISSUE TITLE
Can't set "Other Addresses" record for TRX and XEM

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#645]
Here's what my console looks like just from loading the page of my name "brantly.eth" ([here](https://app.ens.domains/name/brantly.eth))
<img width="1792" alt="Screen Shot 2020-03-26 at 4 27 54 PM" src="https://user-images.githubusercontent.com/30162762/77706196-f24e4680-6f7e-11ea-8d16-b00bdc277aa0.png">

When I try to set my TRX address to "TLmMYWrqXFUsWRFJhWn5azb3RKcXJLbke4" (which I got my TrustWallet account), MetaMask doesn't pop up, and this is what my console looks like (only the bottom 7 lines are new I think)
<img width="1792" alt="Screen Shot 2020-03-26 at 4 28 16 PM" src="https://user-images.githubusercontent.com/30162762/77706423-9801b580-6f7f-11ea-9bae-2cd7ba6df530.png">

The same thing happens when I try to set my XEM address to "NCRLOUUQ5HQYLOD4SHYEZOZAZYQEBHMSXLZYW5KW".

**Comment by makoto** [comment]
Looks like the latest version of address-encoder encodes TRX properly but XEM still has an issue because the decoding returns Uint8Array rather than Buffer.

I  have two options to fix. Let me know which one you want me to do @Arachnid 

- A: Fix [crypto-addr-serialise#b32decode1](https://github.com/ensdomains/crypto-addr-serialize/blob/7ed5647738aada13a572544c06b60c309d779d59/lib/nem-sdk/convert.js#L51) to return buffer instead of Uint8Array by doing `return Buffer.from(b)`
- B: Change [b32decodeXemAddr](https://github.com/ensdomains/address-encoder/blob/master/src/index.ts#L220) from `return ua2hex(b32decode(address))` to `return Buffer.from(b32decode(address))`

**Comment by Arachnid** [comment]
Option A sounds like the better one to me, if it makes it consistent with other functions.

**Comment by makoto** [comment]
Fixed at https://github.com/ensdomains/ens-app/pull/662
