### ISSUE TITLE
creating new subdomain occasionally creates a subdomain with hex decimal numbers

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#67]
In this example, I tried to create "test53" but for some reason it converted into hexdecimal.

![screen shot 2018-12-27 at 17 12 53](https://user-images.githubusercontent.com/2630/50474194-e6ca4380-09fa-11e9-9247-7cab7cbbadc3.png)

This only happens time to time when I tested on ropsten. Never happened when I was testing locally using ganache

**Comment by lyricalpolymath** [comment]
this happened to me too when trying to add a special unicode character as subdomain
and I've also noticed that 

- **the domain shown is actually the 'labelhash' of the string provided**
(the [label](https://docs.ens.domains/contract-api-reference/ens#set-subdomain-owner) is the `keccak256('stringHere')`
you can quickly validate it with this [online Keccak256](https://emn178.github.io/online-tools/keccak_256.html) hash generator

- **the list of subdomains shows only a short name**
but the subdomain that is actually been registered is a long hex address

![Screenshot 2019-05-09 at 12 51 57](https://user-images.githubusercontent.com/516744/57448308-5548c900-7259-11e9-8020-e893473dc78d.jpg)

when clicking it opens the whole label
![Screenshot 2019-05-09 at 12 28 10](https://user-images.githubusercontent.com/516744/57448344-6c87b680-7259-11e9-9138-cf2ec1bbfb4e.jpg)

**Comment by lyricalpolymath** [comment]
actually this **problem happens EVERY time you input a weird name** 
that probably the dictionary checker doesn't have stored and doesn't recognize
then you probably are storing the labelhash as the domain

while you should probably be storing a session variable with the string, and a "pending" state
and when the transaction comes back confirmed, you can then check that that string is the labelhash that is returned and store the string in the subdomain list rather than the labelhash

proof
In tried to add a weird string of random characters `"x56nR2j"`
![Screenshot 2019-05-09 at 13 33 07](https://user-images.githubusercontent.com/516744/57450795-bd9aa900-725f-11e9-816a-46c601e931c3.jpg)

but I've notices that it sanitizes uppercase letters to lowecase letters
so the actual string used is `"x56nr2j"`(with lowecase r )

[Keccak256](https://emn178.github.io/online-tools/keccak_256.html)('x56nr2j') = 41321239322a82a1a5fb45cfa95aa6e61dc8346889f854f4259bf98bacebbc0a

which is exactly what the domain shows
![Screenshot 2019-05-09 at 13 34 33](https://user-images.githubusercontent.com/516744/57451247-0d2da480-7261-11e9-9064-8f0af0dda671.jpg)

@makoto you should probably change the title of the issue to something like:
*creating subdomains with uncommon names (not in the dictionary) shows it's labelhash instead of the domain name*

**Comment by jefflau** [comment]
Not a bug. It's just not in the dictionary
