### ISSUE TITLE
Register, step one is closing ALL windows

### ISSUE THREAD

**Issue by zh** [ensdomains/ens-app#829]
Trying to register on https://ens.domains/ : On step 1, **after paying the gas fee** and **confirming** 2 transactions, **all browser windows were closed**, **including the one with the registration in progress**.
So it is **impossible to continue registration** and needed to start **one more time from the beginning, losing all my ETH**, spend on gas price.

Transactions:
- https://etherscan.io/tx/0x4d78d41fb2ec68d447eba3a38edb80aee76441f8eda2f2db9c477bd15d9a6245
- https://etherscan.io/tx/0xb8ed921b3a7cc080ee2e6a45f4c5772aa213fbba64688685e58244cb50ccf5d7
- https://etherscan.io/tx/0x0666cebd755b508b345e5a597fefba6f4f1c2ecce53044a76bb4fbedda395481 

Environment:
- Site: https://ens.domains/
- Browser: Version 83.0.4103.97 (Official Build) (64-bit)
- Web3 wallet: Metamask

**Comment by jefflau** [comment]
Do you mean app.ens.domains?

Was this on Chrome?

Can you check this out @makoto?

**Comment by zh** [comment]
もう一回視パイしましたけど犯人が見つかった - "Open link in same tab, pop-up as tab" と Metamask が両方があれば ans.domains が使わないーprogress windowはpaymentのwindowと一生にしまってる。
そのチッケトもしまってもいい。

**Comment by kylebakerio** [comment]
Is this fixed? Restarted computer, cannot figure out how to continue registration after completing step 1, assumed I would be able to continue since it says anytime in the next 7 days is fine.

I know I could interact with the contract directly, but I'd rather not reverse engineer it. Is the interface really incapable of handling this scenario still?
