### ISSUE TITLE
Re-add support for [address].addr.reverse

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#931]

**Comment by makoto** [comment]
Can you elaborate? Not quite sure what this means.

**Comment by brantlymillegan** [comment]
> Can you elaborate? Not quite sure what this means.

In the past, a user could search for 0x983110309620D911731Ac0932219af06091b6744.addr.reverse and see info on the reverse record for that address. That functionality is now gone, and I'm assuming it's because of changes made to prep for DNS namespace integration.

**Comment by makoto** [comment]
I just temporarily re-enabled it but doesn't seem to show anything meaningful and ` 0x983110309620D911731Ac0932219af06091b6744.addr.reverse` isn't user friendly representation anyway. What information are you looking for? Reverse record info should be in 'My Name' section in more user friendly way.

**Comment by makoto** [comment]
And this is to @Arachnid 

<img width="909" alt="Screenshot 2020-10-07 at 11 18 43" src="https://user-images.githubusercontent.com/2630/95318918-1aecbc80-088f-11eb-8a21-66ac1c8480a7.png">


The reason reverse record is not listed as valid tld is because I am checkingg if the tld has any owner and `reverse` does not have any (but `addr.reverse` has). Would it be possible to set owner to `reverse` tld if we want to show this rather than hardcoding the logic on `ens-app`?
