### ISSUE TITLE
Avatar thumbnail isn't working anymore in Manager

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#965]
The thumbnail for the image in the avatar text record is no longer showing up in the records or next to the reverse record name on the left (see screenshot below)

![screenshot 1](https://user-images.githubusercontent.com/30162762/97641981-c3fb8280-1a09-11eb-9480-bde6d1f1bd2b.png)

**Comment by jefflau** [comment]
The reason why the avatar is not showing up on your name brantly.eth is because the wp-content url you have is over http. We automatically upgrade this to https so we can show the padlock. To show the avatar, you would need to host the link somewhere that has https.

I've closed this ticket for now pending discussion. But I think the default should be to keep https. The link should actually work if other apps/providers don't require https and the code is actually sound
